### ISSUE TITLE
Dark theme for Rose

### ISSUE THREAD

**Issue by BlackStrikerPD** [Catgrills/Rose#1]
So the dark them isnt working on the Mylist page. The series name are black and doesnt fit for black mode.

**Comment by Catgrills** [comment]
Hello BlackStrikerPD,

Could you provide a screenshot ?

**Comment by BlackStrikerPD** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/63619999/80627116-b57ae100-8a4f-11ea-9f50-906e08afa370.png)

**Comment by Catgrills** [comment]
Hello,

I've updated the script, it should be alright now.
